Fix deployment issues due to NextJS version
[Issue]

On `sst deploy` of the app and upon accessing the SiteUrl, you get an
internal server error. According to logs in the SST console, we get this
error: `Error: Cannot find module 'next/dist\client\components\static-generation-async-storage.external.js'`

[Fix]

Downgrade Next to 13.4.9

Reference:
- https://github.com/vercel/next.js/discussions/56010